import { createStudentHomeFixture, localPortalTestUrl, initializeStudentPage, studentHomeResponse } from './helpers/studentHomeFixture.mjs';
import assert from 'node:assert/strict';
import console from 'node:console';
import { URL } from 'node:url';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';

const base = localPortalTestUrl();
const { date, range, tasks } = createStudentHomeFixture();
const browser = await chromium.launch({ headless: true });
const results = [];
await mkdir('outputs', { recursive: true });
try {
  for (const width of [360, 768, 1440]) {
    const context = await browser.newContext({ viewport: { width, height: 950 }, serviceWorkers: 'block', reducedMotion: 'reduce' });
    const page = await context.newPage();
    const errors = [];
    const writes = [];
    let savedFailure = true;
    page.on('pageerror', (error) => errors.push(error.message));
    await initializeStudentPage(page, date);
    await context.route('**/api/**', async (route) => {
      const path = new URL(route.request().url()).pathname;
      if (route.request().method() !== 'GET') writes.push(path);
      let body = [];
      if (path.endsWith('/quran-tasks/execution')) {
        const payload = route.request().postDataJSON();
        assert.deepEqual(payload.taskIds, [3]);
        tasks[2].studentStatus = payload.status;
        return route.fulfill({ json: { success: true } });
      }
      if (path.endsWith('/site-config')) body = {};
      await route.fulfill(studentHomeResponse(path, { date, range, tasks, savedFailure, body }));
    });
    await page.goto(base);
    await page.locator('.student-home-task').first().waitFor();
    await page.locator('.student-home-today .student-home-task[aria-pressed]').first().waitFor();
    assert.equal(await page.getByRole('navigation', { name: 'تنقل الطالب' }).getByRole('button', { name: 'المصحف', exact: true }).count(), 0);
    assert.equal(await page.getByRole('navigation', { name: 'تنقل الطالب' }).getByRole('button', { name: 'الجلسات', exact: true }).count(), 0);
    const linkTask = page.locator('.student-home-today .student-home-task').filter({ hasText: 'ربط' });
    await linkTask.click();
    await page.waitForFunction(() => globalThis.document.querySelectorAll('.student-home-task[aria-pressed=true]').length === 2);
    assert.equal(await linkTask.getAttribute('aria-pressed'), 'true');
    await linkTask.click();
    await page.waitForFunction(() => globalThis.document.querySelectorAll('.student-home-task[aria-pressed=true]').length === 1);
    await page.locator('.student-home-rank-list>li:visible').first().waitFor();
    assert.equal(await page.locator('.student-home-rank-list>li:visible').count(), width < 900 ? 5 : 10);
    await page.getByRole('button', { name: 'عرض الكل', exact: true }).click();
    assert.equal(await page.locator('.student-home-rank-list>li:visible').count(), width < 900 ? 8 : 16);
    await page.getByRole('button', { name: 'عرض أقل', exact: true }).click();
    assert.equal(await page.getByRole('navigation', { name: 'تنقل الطالب' }).isVisible(), width < 900);
    if (width < 900) {
      const bottom = page.getByRole('navigation', { name: 'تنقل الطالب' });
      await bottom.getByRole('button', { name: 'المتجر', exact: true }).click();
      await page.locator('.student-mobile-screen[aria-label="المتجر"]').waitFor();
      assert.equal(await page.locator('.student-home-window-header').count(), 0);
      assert.equal(await bottom.getByRole('button', { name: 'المتجر', exact: true }).getAttribute('aria-current'), 'page');
      assert.equal(await page.locator('.student-home-header .student-home-store').isVisible(), false);
      await bottom.getByRole('button', { name: 'البرامج', exact: true }).click();
      await page.locator('.student-mobile-screen[aria-label="البرامج"]').waitFor();
      assert.equal(await page.locator('.student-home-window-header').count(), 0);
      await bottom.getByRole('button', { name: 'الرئيسية', exact: true }).click();
      await page.locator('.student-mobile-screen').waitFor({ state: 'detached' });
    }
    assert.equal(await page.getByRole('progressbar', { name: 'إنجاز خطة اليوم' }).getAttribute('aria-valuenow'), '33');
    assert.equal(await page.locator('.student-home-points').count(), 0);
    assert.equal(await page.locator('.student-home-journey').getByText('1,234', { exact: true }).count(), 0, 'Account total belongs only in its popover');
    assert.equal(await page.locator('.student-home-level').innerText(), '');
    assert.equal(await page.locator('.student-home-level svg').count(), 1);
    const layout = await page.locator('.student-home-task').evaluateAll((elements) => elements.map((el) => { const r = el.getBoundingClientRect(); return { x: r.x, y: r.y, height: r.height, width: r.width }; }));
    assert.equal(new Set(layout.map((r) => r.y)).size, 1);
    assert.ok(layout[0].x > layout[1].x && layout[1].x > layout[2].x);
    assert.ok(layout.every((r) => r.width >= 44 && r.height >= 44));
    assert.ok(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.innerWidth));
    await page.screenshot({ path: `outputs/student-home-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: 'قائمة حساب الطالب' }).click();
    await page.locator('.student-home-points').waitFor();
    assert.equal(await page.locator('.student-home-level').evaluate((el) => globalThis.getComputedStyle(el).color), 'rgb(255, 255, 255)');
    assert.equal(await page.locator('.student-home-account-menu').getByText('نقاطي', { exact: true }).count(), 0);
    if (width < 900) assert.deepEqual(await page.locator('.student-home-menu-item').allTextContents(), ['الجلسات', 'المكالمات', 'تسجيل الخروج']);
    assert.ok(await page.locator('.student-home-menu-item').evaluateAll((items) => items.every((el) => globalThis.getComputedStyle(el).justifyContent === 'flex-start')));
    assert.match(await page.locator('.student-home-points').innerText(), /1,234/);
    await page.screenshot({ path: `outputs/student-home-menu-${width}.png` });
    await page.locator('.student-home-account-menu').getByRole('button', { name: 'الجلسات', exact: true }).click();
    assert.equal(await page.getByRole('tab', { name: 'الجلسات', exact: true }).getAttribute('aria-selected'), 'true');
    assert.equal(await page.getByRole('tab', { name: 'الجدول', exact: true }).count(), 0);
    await page.getByRole('tab', { name: 'محفوظي' }).click();
    await page.getByRole('alert').filter({ hasText: 'تعذر تحميل المحفوظ' }).waitFor();
    savedFailure = false;
    await page.getByRole('button', { name: 'إعادة المحاولة', exact: true }).click();
    await page.locator('.student-home-juz summary').last().scrollIntoViewIfNeeded();
    assert.equal(await page.locator('.student-home-juz summary').count(), 29);
    assert.ok(await page.locator('.student-home-window-body').evaluate((element) => element.scrollTop > 0), 'Full memorized list scrolls inside its window');
    await page.locator('.student-home-juz summary').first().click();
    assert.equal(await page.locator('.student-home-juz[open] .student-home-saved-ranges button').count(), 2, 'A missing verse is not reported as memorized');
    await page.screenshot({ path: `outputs/student-home-sessions-${width}.png` });
    await page.getByRole('tab', { name: 'الجلسات', exact: true }).click();
    assert.equal(await page.locator('.student-home-window-header').count(), 0);
    assert.equal(await page.locator('.student-session-week').count(), 1);
    assert.deepEqual(await page.locator('.student-session-columns').first().locator('[data-track]').evaluateAll(nodes => nodes.map(node => node.dataset.track)), ['memorization', 'review', 'link']);
    await page.getByLabel('نقاط اليوم: 43 من 45', { exact: true }).click();
    await page.getByText('الحضور', { exact: true }).waitFor();
    await page.screenshot({ path: `outputs/student-home-evaluation-${width}.png` });
    assert.equal(await page.locator('.student-home-window').getByRole('heading', { name: 'التنفيذ', exact: true }).count(), 0);
    assert.ok(await page.locator('.student-home-window').evaluate((el) => el.scrollWidth <= el.clientWidth));
    await page.getByRole('tab', { name: 'الجلسات', exact: true }).focus();
    await page.keyboard.press('ArrowRight');
    assert.equal(await page.getByRole('tab', { name: 'محفوظي' }).getAttribute('aria-selected'), 'true');
    await page.locator('.student-home-juz[open]').waitFor();
    await page.locator('.student-home-saved-ranges button').first().click();
    await page.getByLabel('مصحف الطالب', { exact: true }).waitFor();
    if (width < 900) assert.equal(await page.locator('.student-home-window-header').count(), 0);
    await page.getByRole('button', { name: 'تفعيل المصحف الداكن', exact: true }).click();
    await page.clock.runFor(300);
    const indexControl = page.getByRole('button', { name: 'فتح فهرس المصحف' });
    assert.equal(await indexControl.evaluate((el) => globalThis.getComputedStyle(el).backgroundColor), 'rgba(255, 255, 255, 0.12)');
    assert.equal(await indexControl.evaluate((el) => globalThis.getComputedStyle(el).color), 'rgb(242, 210, 138)');
    await page.screenshot({ path: `outputs/student-home-reader-dark-${width}.png` });
    await page.getByRole('button', { name: 'تفعيل المصحف الأبيض', exact: true }).click();
    await page.clock.runFor(300);
    assert.equal(await indexControl.evaluate((el) => globalThis.getComputedStyle(el).backgroundColor), 'rgba(255, 255, 255, 0.35)');
    await page.screenshot({ path: `outputs/student-home-reader-${width}.png` });
    const readerTitle = await page.locator('.student-mushaf-toolbar p').first().boundingBox();
    const readerBounds = await page.locator('.student-mushaf-toolbar').boundingBox();
    assert.ok(Math.abs(readerTitle.x + readerTitle.width / 2 - readerBounds.x - readerBounds.width / 2) < 2);
    await page.goBack();
    await page.getByRole('tab', { name: 'محفوظي' }).waitFor();
    await page.locator('.student-home-juz[open]').waitFor();
    assert.equal(await page.locator('.student-home-juz[open]').count(), 1, 'Returning from the reader preserves the open memorized section');
    assert.equal(await page.evaluate(() => globalThis.dispatchEvent(new globalThis.Event('madarij-student-back', { cancelable: true }))), false);
    await page.locator('.student-home-window').waitFor({ state: 'detached' });
    const notificationTrigger = page.locator('.student-home-header').getByRole('button', { name: 'الإشعارات', exact: true });
    const bellBounds = await notificationTrigger.boundingBox();
    const accountBounds = await page.locator('.student-home-level').boundingBox();
    assert.ok(bellBounds.x < accountBounds.x);
    await notificationTrigger.click();
    await page.locator('.student-home-notifications').waitFor();
    assert.equal(await page.locator('.student-home-notifications').getByRole('heading').count(), 0);
    assert.equal(await page.locator('.app-dialog').count(), 0);
    await page.screenshot({ path: `outputs/student-notification-popover-${width}.png` });
    await page.clock.runFor(300);
    await page.keyboard.press('Escape');
    await page.clock.runFor(300);
    await page.getByRole('button', { name: 'قائمة حساب الطالب' }).click();
    assert.ok(await page.locator('.student-home-account-menu').evaluate((el) => el.getBoundingClientRect().width <= 180));
    await page.getByRole('button', { name: 'المكالمات', exact: true }).click();
    await page.getByText('لا توجد غرف مفتوحة حاليًا.', { exact: true }).waitFor();
    assert.equal(await page.locator('.student-home-window-header').count(), 0);
    assert.ok(await page.locator('.student-home-window').evaluate((el) => el.getBoundingClientRect().width <= globalThis.innerWidth));
    assert.equal(await page.locator('.student-mobile-screen').count(), width < 900 ? 1 : 0);
    await page.screenshot({ path: `outputs/student-home-calls-${width}.png` });
    if (width < 900) await page.evaluate(() => globalThis.dispatchEvent(new globalThis.Event('madarij-student-back', { cancelable: true })));
    else await page.keyboard.press('Escape');
    assert.deepEqual(writes.filter((path) => path !== '/api/offline-student/bootstrap' && !path.endsWith('/quran-tasks/execution')), [], 'Browsing only prepares the existing offline workspace; it never submits results');
    assert.deepEqual(errors, []);
    await page.getByRole('button', { name: 'قائمة حساب الطالب' }).click();
    await page.getByRole('button', { name: 'تسجيل الخروج', exact: true }).click();
    await page.locator('.student-home').waitFor({ state: 'detached' });
    assert.equal(await page.evaluate(() => globalThis.localStorage.getItem('wajeh_student_id')), null);
    results.push({ width, rtl: true, overflow: false, sessions: true, points: true, savedRanges: true, writes, errors });
    await context.close();
  }
  await writeFile('outputs/student-home-browser.json', JSON.stringify(results, null, 2));
  console.log(JSON.stringify(results));
} finally { await browser.close(); }
